name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Setup
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: "8.0.x"
        - name: Restore
          run: |
            cd backend
            dotnet restore ./AnyRivals.Web
        - name: Build
          run: |
            cd backend
            dotnet build ./AnyRivals.Web
        - name: Run tests
          run: |
            cd backend
            dotnet test
